# Wavenode test configuration

substitutions:
  devicename: wavenode-test
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_fallback_password: !secret ap_fallback_password
  ota_password: !secret ota_password
  mqtt_broker_name: !secret mqtt_broker
  mqtt_device_root_topic: 9_barbarotto/hamradio/automation/station
  mqtt_root_topic: 9_barbarotto/hamradio/sensors/wavenode/module-1
  ports_short_name: "Wavenode"
  log_level: ERROR

packages:
  board: 
    url: https://github.com/jeffu231/esphome-packages
    file: boards/nodemcu32.yaml
  wifi: 
    url: https://github.com/jeffu231/esphome-packages
    file: common/wifi.yaml
  ota: 
    url: https://github.com/jeffu231/esphome-packages
    file: common/ota.yaml
  mqtt: 
    url: https://github.com/jeffu231/esphome-packages
    file: common/mqtt.yaml
  ads1115-1: 
    url: https://github.com/jeffu231/esphome-packages
    file: sensor/ads1115-0x48.yaml

sensor:
  # Fwd power sensor port 1
  - <<: !include 
      file: ../sensors/wavenode-fwd-sensor.yaml 
      vars: 
        multiplexer_pin: 'A0_GND'
        gain: 2.048
        name: "$ports_short_name 1 FWD"
        adc_id: ads1115_0x48
        id: wavenode_1_fwd
        state_topic: $mqtt_root_topic/port-1/fwd/state
      
      
  #Ref power sensor port 1
  - <<: !include
      file: ../sensors/wavenode-ref-sensor.yaml
      vars: 
        multiplexer_pin: 'A1_GND'
        gain: 2.048
        name: "$ports_short_name 1 REF"
        adc_id: ads1115_0x48
        id: wavenode_1_ref 
        state_topic: $mqtt_root_topic/port-1/ref/state

#SWR Sensor port 1
  - <<: !include
      file: ../sensors/wavenode-swr-sensor.yaml
      vars:
        name: "$ports_short_name 1 SWR"
        id_fwd: wavenode_1_fwd
        id_ref:  wavenode_1_ref
        state_topic: $mqtt_root_topic/port-1/swr/state

    


      


