# variables needed
# name
# id_fwd  id of the fwd power sensor
# id_ref  id of the ref power sensor
# topic_prefix

#SWR Sensor
- platform: template
  name: "$name SWR"
  lambda: |-
    if ( id(${id_fwd}_fwd).state < .1 || id(${id_ref}_ref).state < .1){
      return 1;
    }else{
      return ( 1.0 + sqrt( id(${id_ref}_ref).state / id(${id_fwd}_fwd).state) ) / ( 1.0 - sqrt( id(${id_ref}_ref).state / id(${id_fwd}_fwd).state) );
    }
  update_interval: 100ms
  state_topic: $topic_prefix/swr/state
  filters:
    - delta: 0.1
